"""
JAX-compatible interpolator using ESMF regridding weights.

Adapted (near-verbatim) from jax-esm/jem's
`jem/utils/esmf_regrid.py` (project_jax-esm/jem_repo), reused here as
DomainMaster's ESMF-weight-file regridding backend. Only `ESMFWeights`/
`ESMFRegridder`'s weight-loading is actually consumed by DomainMaster
(EarthSystemGrids/domain_master.py's `_make_esmf_regridder` applies the
loaded weights directly to this repo's own flat `(nface,)` mesh arrays,
bypassing this class's 2D `(n_lon, n_lat)` `__call__`/`apply_batched`
below, which targets JEM's `SlabGrid` convention) -- the rest of this
module (batching, `regrid_xarray`, `inverse`, `diagnostics`, the utility
functions) is kept for fidelity to the original and in case a caller wants
JEM-style 2D usage directly.

This module provides a JAX-friendly interface to apply pre-computed
ESMF regridding weights from netCDF files generated by ESMF_regridweightgen.

Grid shapes and the flat arrays used here follow the SCRIP/ESMF convention
directly: `grid_dims = [n_lon, n_lat]` (longitude varies fastest in the
flat storage, Fortran order), so shapes and reshapes throughout this module
are `(n_lon, n_lat)` with `order='F'` -- matching JEM's `SlabGrid`
convention (`jem/components/slab/grid.py`) with no transpose needed.
"""

from dataclasses import dataclass
from functools import partial
from typing import Any, cast

import jax
import jax.numpy as jnp
import numpy as np
import xarray as xr
from jax import jit


@dataclass
class ESMFWeights:
    """
    Container for ESMF sparse regridding weights.

    ESMF stores weights as a sparse matrix in COO (coordinate) format.
    We store these in a JAX-friendly format for efficient computation.
    """
    # Sparse matrix data (COO format)
    row_indices: jnp.ndarray  # Target grid indices
    col_indices: jnp.ndarray  # Source grid indices
    weights: jnp.ndarray      # Interpolation weights

    # Grid dimensions
    src_shape: tuple[int, ...]
    dst_shape: tuple[int, ...]

    # Optional mask information
    src_mask: jnp.ndarray | None = None
    dst_mask: jnp.ndarray | None = None

    # Metadata
    method: str = "unknown"
    src_grid_dims: tuple[str, ...] | None = None
    dst_grid_dims: tuple[str, ...] | None = None

    @property
    def n_weights(self) -> int:
        """Number of non-zero weights."""
        return len(self.weights)

    @property
    def src_size(self) -> int:
        """Total size of source grid."""
        return int(np.prod(self.src_shape))

    @property
    def dst_size(self) -> int:
        """Total size of destination grid."""
        return int(np.prod(self.dst_shape))


class ESMFRegridder:
    """
    JAX-compatible regridder using ESMF weights.

    This class reads ESMF weight files and provides JIT-compiled
    interpolation functions that work seamlessly in JAX programs.

    Input/output arrays are `(n_lon, n_lat)`, matching `grid_dims` and
    JEM's `SlabGrid` convention directly (Fortran/ESMF order, `order='F'`
    reshape) -- no transpose needed for JEM callers.
    """

    def __init__(self,
        weight_file: str,
        src_shape: tuple[int, ...] | None = None,
        dst_shape: tuple[int, ...] | None = None,
    ):
        """
        Initialize regridder from ESMF weight file.

        ESMF weight files (from ESMF_RegridWeightGen) already carry the
        source/destination grid shapes as `src_grid_dims`/`dst_grid_dims`
        variables (not just n_a/n_b flat sizes), since they're built
        directly from the SCRIP grid files -- so src_shape/dst_shape don't
        need to be supplied by the caller; they're read from the weight
        file itself when not given. The parameters remain as an
        override/validation check for weight files that don't carry this
        metadata.

        Parameters
        ----------
        weight_file : str
            Path to netCDF file generated by ESMF_regridweightgen
        src_shape : tuple of int, optional
            Shape of source grid (n_lon, n_lat). If None, read from the
            weight file's own src_grid_dims variable.
        dst_shape : tuple of int, optional
            Shape of destination grid (n_lon, n_lat). If None, read from
            the weight file's own dst_grid_dims variable.
        """
        self.weight_file = weight_file

        # Load weights (also resolves src_shape/dst_shape if not supplied)
        self.weights = self._load_weights(src_shape, dst_shape)
        self.src_shape = self.weights.src_shape
        self.dst_shape = self.weights.dst_shape

        # Create JIT-compiled interpolation function
        self._interp_fn = jit(self._interpolate_impl)

    def _load_weights(
        self,
        src_shape: tuple[int, ...] | None,
        dst_shape: tuple[int, ...] | None,
    ) -> ESMFWeights:
        """
        Load ESMF weights from netCDF file using xarray.

        ESMF weight files contain:
        - S: sparse weight matrix values
        - col: source (column) indices (1-based in file)
        - row: destination (row) indices (1-based in file)

        `col`/`row` index into src/dst data flattened in SCRIP's native
        Fortran order (the first `grid_dims` axis -- longitude -- varies
        fastest); `grid_dims = [n_lon, n_lat]` already gives this
        regridder's `(n_lon, n_lat)` shape directly, so `order='F'`
        recovers the correct field with no transpose needed.
        `_interpolate_impl` reshapes accordingly.
        """
        # Open dataset with xarray
        ds = xr.open_dataset(self.weight_file)

        try:
            # Read sparse matrix data
            # ESMF uses 1-based indexing, convert to 0-based
            col_indices = ds['col'].values - 1
            row_indices = ds['row'].values - 1
            weights = ds['S'].values

            # Read metadata if available
            method = ds.attrs.get('map_method', 'unknown')

            # Read grid sizes to validate
            src_grid_size = ds.sizes['n_a']
            dst_grid_size = ds.sizes['n_b']

            # Infer src_shape/dst_shape from the weight file's own
            # src_grid_dims/dst_grid_dims variables when not supplied.
            # Those variables are already (n_lon, n_lat), matching this
            # class's convention directly.
            if src_shape is None:
                if 'src_grid_dims' not in ds.variables:
                    raise ValueError(
                        f"'{self.weight_file}' has no src_grid_dims variable and "
                        "no src_shape was supplied -- cannot determine source grid shape."
                    )
                src_shape = tuple(int(n) for n in ds['src_grid_dims'].values)
            if dst_shape is None:
                if 'dst_grid_dims' not in ds.variables:
                    raise ValueError(
                        f"'{self.weight_file}' has no dst_grid_dims variable and "
                        "no dst_shape was supplied -- cannot determine destination grid shape."
                    )
                dst_shape = tuple(int(n) for n in ds['dst_grid_dims'].values)

            # Validate dimensions
            expected_src_size = int(np.prod(src_shape))
            expected_dst_size = int(np.prod(dst_shape))

            if src_grid_size != expected_src_size:
                raise ValueError(
                    f"Source grid size mismatch: file has {src_grid_size}, "
                    f"expected {expected_src_size} from shape {src_shape}"
                )

            if dst_grid_size != expected_dst_size:
                raise ValueError(
                    f"Destination grid size mismatch: file has {dst_grid_size}, "
                    f"expected {expected_dst_size} from shape {dst_shape}"
                )

            # Read masks if available
            src_mask = None
            dst_mask = None

            if 'mask_a' in ds.variables:
                src_mask_flat = ds['mask_a'].values
                src_mask = jnp.array(
                    np.asarray(src_mask_flat).reshape(src_shape, order='F')
                )

            if 'mask_b' in ds.variables:
                dst_mask_flat = ds['mask_b'].values
                dst_mask = jnp.array(
                    np.asarray(dst_mask_flat).reshape(dst_shape, order='F')
                )

            # Try to extract grid dimension names if available
            src_grid_dims = None
            dst_grid_dims = None

            if 'src_grid_dims' in ds.attrs:
                src_grid_dims = tuple(ds.attrs['src_grid_dims'].split(','))
            if 'dst_grid_dims' in ds.attrs:
                dst_grid_dims = tuple(ds.attrs['dst_grid_dims'].split(','))

        finally:
            ds.close()

        # Convert to JAX arrays
        return ESMFWeights(
            row_indices=jnp.array(row_indices, dtype=jnp.int32),
            col_indices=jnp.array(col_indices, dtype=jnp.int32),
            weights=jnp.array(weights, dtype=jnp.float32),
            src_shape=src_shape,
            dst_shape=dst_shape,
            src_mask=src_mask,
            dst_mask=dst_mask,
            method=method,
            src_grid_dims=src_grid_dims,
            dst_grid_dims=dst_grid_dims
        )

    @partial(jit, static_argnums=(0,))
    def _interpolate_impl(self, src_data: jnp.ndarray) -> jnp.ndarray:
        """
        Core interpolation implementation (JIT-compiled).

        Applies sparse matrix multiplication: dst = W @ src
        where W is the sparse weight matrix.

        `col`/`row` index into src/dst flattened in Fortran order (see
        `_load_weights`), so the flatten/reshape here must use order='F' to
        stay aligned with those indices.
        """
        # Flatten source data (Fortran order -- see docstring)
        src_flat = src_data.reshape(-1, order='F')

        # Apply sparse matrix multiplication using scatter-add
        # This is equivalent to: dst[row] += weight * src[col]
        dst_flat = jnp.zeros(self.weights.dst_size, dtype=src_data.dtype)

        # Gather source values and multiply by weights
        src_values = src_flat[self.weights.col_indices]
        weighted_values = src_values * self.weights.weights

        # Scatter-add to destination
        dst_flat = dst_flat.at[self.weights.row_indices].add(weighted_values)

        # Reshape to destination grid (Fortran order -- see docstring)
        return dst_flat.reshape(self.weights.dst_shape, order='F')

    def __call__(self, src_data: jnp.ndarray) -> jnp.ndarray:
        """
        Interpolate data from source grid to destination grid.

        Parameters
        ----------
        src_data : jnp.ndarray
            Data on source grid with shape matching src_shape

        Returns
        -------
        jnp.ndarray
            Interpolated data on destination grid
        """
        # Validate input shape
        #if src_data.shape != self.src_shape:
        #    raise ValueError(
        #        f"Input shape {src_data.shape} does not match "
        #        f"expected source shape {self.src_shape}"
        #    )

        return cast(jnp.ndarray, self._interp_fn(src_data))

    def apply_batched(self, src_data: jnp.ndarray,
                      batch_dims: int = 1) -> jnp.ndarray:
        """
        Apply interpolation to batched data.

        Parameters
        ----------
        src_data : jnp.ndarray
            Data with leading batch dimensions followed by grid shape
            e.g., (time, level, lat, lon) or (batch, lat, lon)
        batch_dims : int
            Number of leading batch dimensions

        Returns
        -------
        jnp.ndarray
            Interpolated data with same batch dimensions
        """
        # Validate shape
        expected_shape = src_data.shape[:batch_dims] + self.src_shape
        if src_data.shape != expected_shape:
            raise ValueError(
                f"Input shape {src_data.shape} incompatible with "
                f"batch_dims={batch_dims} and src_shape={self.src_shape}"
            )

        # Vectorize over batch dimensions
        vectorized_interp = self._interp_fn
        for _ in range(batch_dims):
            vectorized_interp = jax.vmap(vectorized_interp)

        return cast(jnp.ndarray, vectorized_interp(src_data))

    def regrid_xarray(self, da: xr.DataArray,
                      target_coords: dict[str, np.ndarray] | None = None) -> xr.DataArray:
        """
        Regrid an xarray DataArray and preserve metadata.

        Parameters
        ----------
        da : xr.DataArray
            Input data array with dimensions matching src_shape
        target_coords : dict, optional
            Target coordinates for output DataArray

        Returns
        -------
        xr.DataArray
            Regridded data with updated coordinates
        """
        # Extract batch dimensions (everything before the last N dims matching src_shape)
        batch_dims = da.dims[:-len(self.src_shape)]

        # Get data as numpy/jax array
        data = jnp.array(da.values)

        # Apply regridding
        if len(batch_dims) > 0:
            result = self.apply_batched(data, batch_dims=len(batch_dims))
        else:
            result = self(data)

        # Create output coordinates
        out_coords = {}

        # Keep batch coordinates
        for dim in batch_dims:
            out_coords[dim] = da.coords[dim]

        # Add target grid coordinates
        if target_coords is not None:
            out_coords.update(target_coords)
        elif self.weights.dst_grid_dims is not None:
            # Use stored dimension names if available
            for i, dim_name in enumerate(self.weights.dst_grid_dims):
                out_coords[dim_name] = np.arange(self.dst_shape[i])
        else:
            # Create generic dimension names
            for i, size in enumerate(self.dst_shape):
                dim_name = f"dim_{i}"
                out_coords[dim_name] = np.arange(size)

        # Determine output dimensions
        if self.weights.dst_grid_dims is not None:
            out_dims = batch_dims + self.weights.dst_grid_dims
        else:
            grid_dim_names = tuple(f"dim_{i}" for i in range(len(self.dst_shape)))
            out_dims = batch_dims + grid_dim_names

        # Create output DataArray
        result_da = xr.DataArray(
            np.array(result),
            dims=out_dims,
            coords=out_coords,
            attrs=da.attrs.copy()
        )

        # Add regridding metadata
        result_da.attrs['regrid_method'] = self.weights.method
        result_da.attrs['regrid_source_shape'] = str(self.src_shape)
        result_da.attrs['regrid_target_shape'] = str(self.dst_shape)

        return result_da

    def inverse(self) -> 'ESMFRegridder':
        """
        Create approximate inverse regridder (dst -> src).

        Note: This creates a new weight structure by swapping row/col indices.
        For true conservative remapping inverse, regenerate weights with ESMF.
        """
        inverse_weights = ESMFWeights(
            row_indices=self.weights.col_indices,
            col_indices=self.weights.row_indices,
            weights=self.weights.weights,
            src_shape=self.weights.dst_shape,
            dst_shape=self.weights.src_shape,
            src_mask=self.weights.dst_mask,
            dst_mask=self.weights.src_mask,
            method=f"inverse_{self.weights.method}",
            src_grid_dims=self.weights.dst_grid_dims,
            dst_grid_dims=self.weights.src_grid_dims
        )

        # Create new regridder with swapped weights
        inv_regridder = ESMFRegridder.__new__(ESMFRegridder)
        inv_regridder.weight_file = f"inverse_of_{self.weight_file}"
        inv_regridder.src_shape = self.dst_shape
        inv_regridder.dst_shape = self.src_shape
        inv_regridder.weights = inverse_weights
        inv_regridder._interp_fn = jit(inv_regridder._interpolate_impl)

        return inv_regridder

    def diagnostics(self) -> dict[str, Any]:
        """Return diagnostic information about the regridder."""
        return {
            'method': self.weights.method,
            'src_shape': self.weights.src_shape,
            'dst_shape': self.weights.dst_shape,
            'src_size': self.weights.src_size,
            'dst_size': self.weights.dst_size,
            'n_weights': self.weights.n_weights,
            'sparsity': self.weights.n_weights / (self.weights.src_size * self.weights.dst_size),
            'avg_stencil_size': self.weights.n_weights / self.weights.dst_size,
            'has_src_mask': self.weights.src_mask is not None,
            'has_dst_mask': self.weights.dst_mask is not None,
        }


# ============================================================================
# Utility Functions
# ============================================================================

def create_regridder_pair(
    src_to_dst_file: str,
    dst_to_src_file: str,
    src_shape: tuple[int, ...],
    dst_shape: tuple[int, ...]
) -> tuple[ESMFRegridder, ESMFRegridder]:
    """
    Create a pair of regridders for bidirectional interpolation.

    Parameters
    ----------
    src_to_dst_file : str
        Weight file for source to destination
    dst_to_src_file : str
        Weight file for destination to source
    src_shape : tuple
        Source grid shape
    dst_shape : tuple
        Destination grid shape

    Returns
    -------
    forward_regridder, backward_regridder
    """
    forward = ESMFRegridder(src_to_dst_file, src_shape, dst_shape)
    backward = ESMFRegridder(dst_to_src_file, dst_shape, src_shape)

    return forward, backward


def create_regridder_from_xarray(
    weight_file: str,
    src_da: xr.DataArray,
    dst_da: xr.DataArray
) -> ESMFRegridder:
    """
    Create regridder inferring shapes from xarray DataArrays.

    Parameters
    ----------
    weight_file : str
        Path to ESMF weight file
    src_da : xr.DataArray
        Example source data array
    dst_da : xr.DataArray
        Example destination data array

    Returns
    -------
    ESMFRegridder
    """
    src_shape = src_da.shape
    dst_shape = dst_da.shape

    return ESMFRegridder(weight_file, src_shape, dst_shape)


def verify_conservation(
    regridder: ESMFRegridder,
    src_data: jnp.ndarray,
    src_areas: jnp.ndarray | None = None,
    dst_areas: jnp.ndarray | None = None
) -> dict[str, float]:
    """
    Verify conservation properties of regridding.

    Parameters
    ----------
    regridder : ESMFRegridder
        The regridder to test
    src_data : jnp.ndarray
        Test data on source grid
    src_areas : jnp.ndarray, optional
        Cell areas on source grid
    dst_areas : jnp.ndarray, optional
        Cell areas on destination grid

    Returns
    -------
    dict
        Conservation diagnostics
    """
    dst_data = regridder(src_data)

    # Calculate integrals
    if src_areas is not None:
        src_integral = jnp.sum(src_data * src_areas)
    else:
        src_integral = jnp.sum(src_data)

    if dst_areas is not None:
        dst_integral = jnp.sum(dst_data * dst_areas)
    else:
        dst_integral = jnp.sum(dst_data)

    # Calculate errors
    abs_error = dst_integral - src_integral
    if jnp.abs(src_integral) > 1e-10:
        rel_error = abs_error / src_integral
    else:
        rel_error = abs_error

    return {
        'src_integral': float(src_integral),
        'dst_integral': float(dst_integral),
        'absolute_error': float(abs_error),
        'relative_error': float(rel_error),
        'conserves': float(jnp.abs(rel_error)) < 1e-6
    }
